Test member page data
everypolitician-scrapers/nigeria-national-assembly pull request #17
Opened 2017-04-27 10:15 UTC by ondenman

Tests scraper output against YAML file.
MemberPage#to_h should match the data specified in the YAML.

Part of everypolitician/everypolitician#600 (Ensure every scraper that has been ported to Scraped has a basic YAML test for at least one person)

2017-04-28 09:45 UTC, tmtmtmtm requested changes

2017-04-28 09:45 UTC, tmtmtmtm commented on test/data/664.yml
> +  :position: ''
Again, it's worth making sure that every field is covered by at least one test case.

2017-04-28 09:45 UTC, tmtmtmtm commented on Rakefile
> +task default: %w(rubocop test)
this looks like you're running the old version of rubocop here. Is the plan to update that separately?

2017-04-28 09:55 UTC, ondenman commented on Rakefile
> +task default: %w(rubocop test)
I've opened a PR for this. https://github.com/everypolitician-scrapers/nigeria-national-assembly/pull/18

2017-05-16 14:04 UTC, closed without merging

2017-05-16 14:17 UTC, ondenman commented
Github closed this PR after I rebased and force pushed. Not sure why.

I've opened a new PR: https://github.com/everypolitician-scrapers/nigeria-national-assembly/pull/20