Test member data  refactor
everypolitician-scrapers/nigeria-national-assembly pull request #20
Opened 2017-05-16 14:16 UTC by ondenman

2017-05-23 10:32 UTC, tmtmtmtm requested changes
@ondenman can I ask you to give this a better title? At the minute it's a bit of a word salad, which makes it quite hard to know what it's meant to be doing. Is this testing the "member data refactor"? Refactoring the "test member data"? Neither of them seem to match what's actually going on…

2017-05-23 10:59 UTC, tmtmtmtm requested changes
Generally looking good, but I think we need a few more test cases. In general we should make sure that any combination we explicitly code for is covered somewhere, to avoid any regressions later on those parts.

2017-05-23 10:59 UTC, tmtmtmtm commented on lib/member_page.rb
> +    image_url.include?('/avatar.jpg') ? nil : image_url
Would be good to make sure this is covered

2017-05-23 10:59 UTC, tmtmtmtm commented on lib/member_page.rb
> +    constituency.empty? ? '' : [constituency, state].join(', ')
the 'empty' side of this doesn't seem to be covered

2017-05-23 10:59 UTC, tmtmtmtm commented on lib/member_page.rb
> +  TITLE_RE = /^(Hon\.|Sen\.) /
Both tests at the minute are for Hon., and none for Sen.

2017-06-05 11:37 UTC, ondenman commented on lib/member_page.rb
> +  TITLE_RE = /^(Hon\.|Sen\.) /
I've added the additional tests and will rebase to bring the branch up to date with master.

2017-06-05 11:41 UTC, ondenman commented on lib/member_page.rb
> +    image_url.include?('/avatar.jpg') ? nil : image_url
Added in aacd30d

2017-06-05 11:41 UTC, ondenman commented on lib/member_page.rb
> +    constituency.empty? ? '' : [constituency, state].join(', ')
Added in 6763788

2017-06-05 11:41 UTC, ondenman commented on lib/member_page.rb
> +  TITLE_RE = /^(Hon\.|Sen\.) /
Added in 77bebab

2017-07-04 10:51 UTC, tmtmtmtm approved these changes

2017-07-04 10:51 UTC, merged